services:
  data-migrate:
    build:
      context: ./data-service
      dockerfile: ../docker/data-service/Dockerfile.dev
    volumes:
      - ./data-service:/app
    command: ["go", "run", "./cmd/migrate"]
    depends_on:
      - data-db
    env_file: .env
    restart: on-failure

  data-api:
    build:
      context: ./data-service
      dockerfile: ../docker/data-service/Dockerfile.dev
    ports:
      - "${HTTP_FORWARD_PORT:-8080}:${HTTP_PORT:-8080}"
    volumes:
      - ./data-service:/app
      - ./tmp:/app/tmp
    depends_on:
      data-migrate:
        condition: service_completed_successfully
    env_file: .env
    restart: always

  data-worker:
    build:
      context: ./data-service
      dockerfile: ../docker/data-service/Dockerfile.dev
    volumes:
      - ./data-service:/app
      - ./tmp:/app/tmp
    command: ["air", "-c", ".air.worker.toml"]
    depends_on:
      data-migrate:
        condition: service_completed_successfully
    env_file: .env
    restart: always

  ml-api:
    build:
      context: ./ML
      dockerfile: ../docker/ml/Dockerfile.dev
    volumes:
      - ./ML:/app
      - ./ML/models:/app/models
      - ./ML/data:/app/data:ro
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - ml-api
    restart: always

  data-db:
    image: postgres:15-alpine
    ports:
      - ${DATABASE_PORT:-5555}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres1}
      - POSTGRES_DB=${DATABASE_DATABASE:-postgres}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
